export type Difficulty = "Easy" | "Medium" | "Hard";

export type VideoDetail = {
  id: number;
  title: string;
  youtubeId?: string; // YouTube video ID for instant iframe embed
  youtubeUrl?: string;
  leetcodeNum?: number;
  leetcodeTitle?: string;
  leetcodeUrl?: string;
  difficulty?: Difficulty;
  companies?: string[];
  pattern?: string;
  summary?: string;
  codeUrl?: string;
};

// Curated problem data for codestorywithMIK playlists
export const videoDetailsMap: Record<string, Record<number, VideoDetail>> = {
  "cpp-stl-java-jcf": {
    1: {
      id: 1,
      title: "Matrix Diagonal Sum (Using STL / JCF)",
      leetcodeNum: 1572,
      leetcodeTitle: "Matrix Diagonal Sum",
      leetcodeUrl: "https://leetcode.com/problems/matrix-diagonal-sum/",
      difficulty: "Easy",
      companies: ["Google", "Amazon"],
      pattern: "Matrix Diagonal Traversal",
      summary: "Iterate once: primary diagonal at (i, i) and secondary diagonal at (i, n - 1 - i). Subtract center element if n is odd.",
    },
    2: {
      id: 2,
      title: "Find Smallest Letter Greater Than Target",
      leetcodeNum: 744,
      leetcodeTitle: "Find Smallest Letter Greater Than Target",
      leetcodeUrl: "https://leetcode.com/problems/find-smallest-letter-greater-than-target/",
      difficulty: "Easy",
      companies: ["Amazon", "LinkedIn"],
      pattern: "Binary Search / Upper Bound",
      summary: "Apply std::upper_bound or binary search on sorted characters. Use modulo arithmetic (idx % n) to handle wrap-around.",
    },
    3: {
      id: 3,
      title: "Largest Number (Custom Comparator)",
      leetcodeNum: 179,
      leetcodeTitle: "Largest Number",
      leetcodeUrl: "https://leetcode.com/problems/largest-number/",
      difficulty: "Medium",
      companies: ["Amazon", "Google", "Microsoft"],
      pattern: "Custom Comparator Sorting",
      summary: "Sort string numbers with custom comparator: (s1 + s2) > (s2 + s1). Check for all zeros ['0','0'] edge case.",
    },
    4: {
      id: 4,
      title: "Length of Last Word",
      leetcodeNum: 58,
      leetcodeTitle: "Length of Last Word",
      leetcodeUrl: "https://leetcode.com/problems/length-of-last-word/",
      difficulty: "Easy",
      companies: ["Amazon", "Apple"],
      pattern: "Reverse Iterators / Two Pointers",
      summary: "Traverse from back of string, skip trailing spaces, then count characters until the next space or start of string.",
    },
    5: {
      id: 5,
      title: "Find First Palindromic String in the Array",
      leetcodeNum: 2108,
      leetcodeTitle: "Find First Palindromic String in the Array",
      leetcodeUrl: "https://leetcode.com/problems/find-first-palindromic-string-in-the-array/",
      difficulty: "Easy",
      companies: ["Adobe", "Google"],
      pattern: "String / Two Pointers",
      summary: "Check words sequentially using two pointers or std::equal with reverse iterators. Return first valid palindrome.",
    },
    6: {
      id: 6,
      title: "Vowels Game in a String",
      leetcodeNum: 3227,
      leetcodeTitle: "Vowels Game in a String",
      leetcodeUrl: "https://leetcode.com/problems/vowels-game-in-a-string/",
      difficulty: "Medium",
      companies: ["Amazon"],
      pattern: "Game Theory / Parity",
      summary: "If there is at least one vowel in the string, Alice can always win on the first turn. Bob wins only if vowel count is 0.",
    },
    9: {
      id: 9,
      title: "Maximum Difference by Remapping a Digit",
      leetcodeNum: 2566,
      leetcodeTitle: "Maximum Difference by Remapping a Digit",
      leetcodeUrl: "https://leetcode.com/problems/maximum-difference-by-remapping-a-digit/",
      difficulty: "Easy",
      companies: ["Amazon"],
      pattern: "Greedy String Transformation",
      summary: "To maximize, replace the first non-9 digit with 9. To minimize, replace the first digit with 0. Return difference.",
    },
  },

  "difference-array-technique": {
    1: {
      id: 1,
      title: "Difference Array Technique: Concept & Fundamentals",
      youtubeId: "ZHNVmtm08WY",
      leetcodeNum: 370,
      leetcodeTitle: "Range Addition",
      leetcodeUrl: "https://leetcode.com/problems/range-addition/",
      difficulty: "Medium",
      companies: ["Google", "Meta"],
      pattern: "Difference Array",
      summary: "Master the fundamental idea: add value at start index, subtract at end+1 index, then compute prefix sum in O(N).",
    },
    2: {
      id: 2,
      title: "Shifting Letters II",
      youtubeId: "x0WsmvQ_l3g",
      leetcodeNum: 2381,
      leetcodeTitle: "Shifting Letters II",
      leetcodeUrl: "https://leetcode.com/problems/shifting-letters-ii/",
      difficulty: "Medium",
      companies: ["Amazon", "Google"],
      pattern: "Difference Array",
      summary: "Apply range updates for forward (+1) and backward (-1) character shifts with modular arithmetic.",
    },
    3: {
      id: 3,
      title: "Increment Submatrices by One (2D Difference Array)",
      youtubeId: "j42_qgIvhHw",
      leetcodeNum: 2536,
      leetcodeTitle: "Increment Submatrices by One",
      leetcodeUrl: "https://leetcode.com/problems/increment-submatrices-by-one/",
      difficulty: "Medium",
      companies: ["Amazon", "Microsoft"],
      pattern: "2D Difference Array",
      summary: "Extend difference array to 2D matrices: update boundaries for rows or 2D prefix sums.",
    },
    4: {
      id: 4,
      title: "Car Pooling",
      youtubeId: "k_Q5cI1_s0g",
      leetcodeNum: 1094,
      leetcodeTitle: "Car Pooling",
      leetcodeUrl: "https://leetcode.com/problems/car-pooling/",
      difficulty: "Medium",
      companies: ["Amazon", "Uber", "DoorDash"],
      pattern: "Difference Array / Sweep",
      summary: "Add passengers at pickup location and drop off at destination, verify capacity at each mile.",
    },
    5: {
      id: 5,
      title: "Corporate Flight Bookings",
      youtubeId: "G-k0TeqU1Gk",
      leetcodeNum: 1109,
      leetcodeTitle: "Corporate Flight Bookings",
      leetcodeUrl: "https://leetcode.com/problems/corporate-flight-bookings/",
      difficulty: "Medium",
      companies: ["Expedia", "Bloomberg"],
      pattern: "Difference Array",
      summary: "Direct application of 1D Difference Array: seats booked from first to last flight.",
    },
    6: {
      id: 6,
      title: "Zero Array Transformation I & III",
      youtubeId: "tV1vW6YdE1Y",
      leetcodeNum: 3362,
      leetcodeTitle: "Zero Array Transformation III",
      leetcodeUrl: "https://leetcode.com/problems/zero-array-transformation-iii/",
      difficulty: "Medium",
      companies: ["Google", "PhonePe"],
      pattern: "Difference Array + Greedy Heap",
      summary: "Combine difference array technique with a max-heap to greedily pick optimal queries.",
    },
    7: {
      id: 7,
      title: "Difference Array with Jumps Technique",
      youtubeId: "ZHNVmtm08WY",
      leetcodeNum: 2772,
      leetcodeTitle: "Apply Operations to Make All Array Elements Equal to Zero",
      leetcodeUrl: "https://leetcode.com/problems/apply-operations-to-make-all-array-elements-equal-to-zero/",
      difficulty: "Medium",
      companies: ["Meta", "Apple"],
      pattern: "Sliding Difference Array",
      summary: "Apply updates of fixed window length k across the array using a running difference accumulator.",
    },
    8: {
      id: 8,
      title: "XOR After Range Multiplication Queries",
      youtubeId: "ZHNVmtm08WY",
      leetcodeNum: 3655,
      leetcodeTitle: "XOR After Range Multiplication Queries II",
      leetcodeUrl: "https://leetcode.com/problems/xor-after-range-multiplication-queries-ii/",
      difficulty: "Hard",
      companies: ["Google"],
      pattern: "Difference Array + Bitwise",
      summary: "Advanced range manipulation utilizing difference array principles over bit positions.",
    },
    9: {
      id: 9,
      title: "Difference Array vs Line Sweep Technique: When to use what?",
      youtubeId: "ZHNVmtm08WY",
      leetcodeNum: 253,
      leetcodeTitle: "Meeting Rooms II",
      leetcodeUrl: "https://leetcode.com/problems/meeting-rooms-ii/",
      difficulty: "Medium",
      companies: ["Google", "Amazon", "Bloomberg"],
      pattern: "Concept Comparison",
      summary: "Deep dive into when to index directly via difference array vs sorting timestamps in a line sweep.",
    },
    10: {
      id: 10,
      title: "Summary & Tricky Edge Cases in Difference Arrays",
      youtubeId: "ZHNVmtm08WY",
      leetcodeNum: 1893,
      leetcodeTitle: "Check if All the Integers in a Range Are Covered",
      leetcodeUrl: "https://leetcode.com/problems/check-if-all-the-integers-in-a-range-are-covered/",
      difficulty: "Easy",
      companies: ["Google"],
      pattern: "Difference Array",
      summary: "Check range overlaps and edge conditions; complete mastery recap for interviews.",
    },
  },

  "two-pointers": {
    1: {
      id: 1,
      title: "Two Sum II - Input Array Is Sorted",
      youtubeId: "cQ1Oz4ckcMT",
      leetcodeNum: 167,
      leetcodeTitle: "Two Sum II - Input Array Is Sorted",
      leetcodeUrl: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
      difficulty: "Medium",
      companies: ["Amazon", "Google", "Apple"],
      pattern: "Two Pointers - Opposite Ends",
      summary: "Start pointers at opposite ends: if sum is too small increment left, if too large decrement right.",
    },
    2: {
      id: 2,
      title: "3Sum (All Unique Triplets)",
      youtubeId: "jzZsG8n2R9A",
      leetcodeNum: 15,
      leetcodeTitle: "3Sum",
      leetcodeUrl: "https://leetcode.com/problems/3sum/",
      difficulty: "Medium",
      companies: ["Meta", "Amazon", "Microsoft", "Google"],
      pattern: "Two Pointers - Opposite Ends",
      summary: "Sort array, fix one element, and use two pointers to find remaining pair. Skip duplicates carefully.",
    },
    3: {
      id: 3,
      title: "3Sum Closest",
      youtubeId: "h_P1E4i9dC8",
      leetcodeNum: 16,
      leetcodeTitle: "3Sum Closest",
      leetcodeUrl: "https://leetcode.com/problems/3sum-closest/",
      difficulty: "Medium",
      companies: ["Amazon", "Bloomberg", "Google"],
      pattern: "Two Pointers - Opposite Ends",
      summary: "Track the closest running sum to target while narrowing left and right pointers.",
    },
    4: {
      id: 4,
      title: "4Sum",
      youtubeId: "4ggF3tXIAvc",
      leetcodeNum: 18,
      leetcodeTitle: "4Sum",
      leetcodeUrl: "https://leetcode.com/problems/4sum/",
      difficulty: "Medium",
      companies: ["Amazon", "Apple", "Microsoft"],
      pattern: "Two Pointers - K-Sum",
      summary: "Generalize 3Sum with 2 nested loops + two pointers. Watch out for integer overflow when summing.",
    },
    5: {
      id: 5,
      title: "Container With Most Water",
      youtubeId: "UuiTKBwPgAo",
      leetcodeNum: 11,
      leetcodeTitle: "Container With Most Water",
      leetcodeUrl: "https://leetcode.com/problems/container-with-most-water/",
      difficulty: "Medium",
      companies: ["Amazon", "Google", "Meta", "Adobe"],
      pattern: "Two Pointers - Greedy",
      summary: "Width shrinks with every step, so greedily move the pointer pointing to the shorter vertical bar.",
    },
    6: {
      id: 6,
      title: "Trapping Rain Water",
      youtubeId: "ZI2z5pq0TqA",
      leetcodeNum: 42,
      leetcodeTitle: "Trapping Rain Water",
      leetcodeUrl: "https://leetcode.com/problems/trapping-rain-water/",
      difficulty: "Hard",
      companies: ["Amazon", "Google", "Goldman Sachs", "Microsoft"],
      pattern: "Two Pointers - Min-Max Bounds",
      summary: "Maintain leftMax and rightMax bounds with two pointers to achieve optimal O(N) time and O(1) space.",
    },
    7: {
      id: 7,
      title: "Maximum Width Ramp",
      youtubeId: "k99r1A7krcY",
      leetcodeNum: 962,
      leetcodeTitle: "Maximum Width Ramp",
      leetcodeUrl: "https://leetcode.com/problems/maximum-width-ramp/",
      difficulty: "Medium",
      companies: ["Google", "Amazon"],
      pattern: "Two Pointers + Right Max Array",
      summary: "Precompute max-from-right or use monotonic stack, then expand window to find maximum j - i.",
    },
    8: {
      id: 8,
      title: "Minimize Maximum Pair Sum in Array",
      youtubeId: "7eLMOE1jnls",
      leetcodeNum: 1877,
      leetcodeTitle: "Minimize Maximum Pair Sum in Array",
      leetcodeUrl: "https://leetcode.com/problems/minimize-maximum-pair-sum-in-array/",
      difficulty: "Medium",
      companies: ["Amazon"],
      pattern: "Two Pointers - Greedy Sorting",
      summary: "Sort array and pair smallest with largest element to minimize the maximum pair sum.",
    },
    9: {
      id: 9,
      title: "Partition Labels",
      youtubeId: "ED4ateJu86I",
      leetcodeNum: 763,
      leetcodeTitle: "Partition Labels",
      leetcodeUrl: "https://leetcode.com/problems/partition-labels/",
      difficulty: "Medium",
      companies: ["Amazon", "Google"],
      pattern: "Two Pointers - Greedy Range",
      summary: "Record the last occurrence of each character, extend the current partition end pointer as far as needed.",
    },
    10: {
      id: 10,
      title: "Reverse Words in a String",
      youtubeId: "vhnRAaJybpA",
      leetcodeNum: 151,
      leetcodeTitle: "Reverse Words in a String",
      leetcodeUrl: "https://leetcode.com/problems/reverse-words-in-a-string/",
      difficulty: "Medium",
      companies: ["Microsoft", "Amazon", "Apple"],
      pattern: "Two Pointers - In-Place String",
      summary: "Clean multiple spaces, reverse the entire string, then reverse each individual word in place.",
    },
    11: {
      id: 11,
      title: "Move Zeroes",
      youtubeId: "1P_e85354nE",
      leetcodeNum: 283,
      leetcodeTitle: "Move Zeroes",
      leetcodeUrl: "https://leetcode.com/problems/move-zeroes/",
      difficulty: "Easy",
      companies: ["Meta", "Apple", "Amazon"],
      pattern: "Two Pointers - Fast & Slow",
      summary: "Slow pointer points to next insertion position for non-zero numbers; fill remaining with zero.",
    },
    12: {
      id: 12,
      title: "Remove Duplicates from Sorted Array",
      youtubeId: "DEJAZBq0FDA",
      leetcodeNum: 26,
      leetcodeTitle: "Remove Duplicates from Sorted Array",
      leetcodeUrl: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
      difficulty: "Easy",
      companies: ["Microsoft", "Google"],
      pattern: "Two Pointers - Fast & Slow",
      summary: "Advance fast pointer and overwrite slow pointer only when a new distinct value is encountered.",
    },
    13: {
      id: 13,
      title: "Squares of a Sorted Array",
      youtubeId: "4ggF3tXIAvc",
      leetcodeNum: 977,
      leetcodeTitle: "Squares of a Sorted Array",
      leetcodeUrl: "https://leetcode.com/problems/squares-of-a-sorted-array/",
      difficulty: "Easy",
      companies: ["Meta", "Amazon", "Uber"],
      pattern: "Two Pointers - Opposite Ends",
      summary: "Compare squares at left and right extremities, place the larger square at the end of output array.",
    },
    14: {
      id: 14,
      title: "Find the Lexicographically Largest String From the Box I",
      youtubeId: "k99r1A7krcY",
      leetcodeNum: 3403,
      leetcodeTitle: "Find the Lexicographically Largest String From the Box I",
      leetcodeUrl: "https://leetcode.com/problems/find-the-lexicographically-largest-string-from-the-box-i/",
      difficulty: "Medium",
      companies: ["Google"],
      pattern: "Two Pointers - String Slicing",
      summary: "Find optimal substring start index using two pointers and compare candidates lexicographically.",
    },
    15: {
      id: 15,
      title: "Count the Number of Good Partitions",
      youtubeId: "k99r1A7krcY",
      leetcodeNum: 2963,
      leetcodeTitle: "Count the Number of Good Partitions",
      leetcodeUrl: "https://leetcode.com/problems/count-the-number-of-good-partitions/",
      difficulty: "Hard",
      companies: ["Google", "Amazon"],
      pattern: "Two Pointers - Interval Merging",
      summary: "Merge intervals defined by first and last index of each element, then compute 2^(intervals - 1).",
    },
  },

  "sliding-window": {
    1: {
      id: 1,
      title: "Sliding Window Core Blueprint & First Negative in Window of Size K",
      youtubeId: "mrUBUWb23hk",
      leetcodeNum: 1456,
      leetcodeTitle: "Maximum Number of Vowels in a Substring of Given Length",
      leetcodeUrl: "https://leetcode.com/problems/maximum-number-of-vowels-in-a-substring-of-given-length/",
      difficulty: "Medium",
      companies: ["Amazon", "Google"],
      pattern: "Fixed Size Window",
      summary: "Standard fixed window pattern: slide window by adding incoming element and removing outgoing element.",
    },
    3: {
      id: 3,
      title: "Find All Anagrams in a String",
      youtubeId: "fYgU6Bi2fYY",
      leetcodeNum: 438,
      leetcodeTitle: "Find All Anagrams in a String",
      leetcodeUrl: "https://leetcode.com/problems/find-all-anagrams-in-a-string/",
      difficulty: "Medium",
      companies: ["Microsoft", "Google", "Amazon"],
      pattern: "Fixed Size Window + Hash Array",
      summary: "Maintain frequency count array of size 26 for pattern p and sliding window in s.",
    },
    4: {
      id: 4,
      title: "Fruit Into Baskets",
      youtubeId: "s_zu2Mr9P30",
      leetcodeNum: 904,
      leetcodeTitle: "Fruit Into Baskets",
      leetcodeUrl: "https://leetcode.com/problems/fruit-into-baskets/",
      difficulty: "Medium",
      companies: ["Google", "Amazon"],
      pattern: "Variable Size Window",
      summary: "Find length of longest subarray with at most 2 distinct elements using a frequency map.",
    },
    5: {
      id: 5,
      title: "Longest Substring Without Repeating Characters",
      youtubeId: "wiGpQwVHdE0",
      leetcodeNum: 3,
      leetcodeTitle: "Longest Substring Without Repeating Characters",
      leetcodeUrl: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
      difficulty: "Medium",
      companies: ["Amazon", "Microsoft", "Google", "Meta", "Bloomberg"],
      pattern: "Variable Size Window",
      summary: "Expand right pointer; when duplicate seen, advance left pointer past the previous index of the duplicate.",
    },
    6: {
      id: 6,
      title: "Max Consecutive Ones III",
      youtubeId: "3E4JBHSLpYk",
      leetcodeNum: 1004,
      leetcodeTitle: "Max Consecutive Ones III",
      leetcodeUrl: "https://leetcode.com/problems/max-consecutive-ones-iii/",
      difficulty: "Medium",
      companies: ["Meta", "Google", "Uber"],
      pattern: "Variable Size Window",
      summary: "Allow at most k zeroes in the window. Shrink window from left whenever zero count exceeds k.",
    },
    7: {
      id: 7,
      title: "Minimum Size Subarray Sum",
      youtubeId: "jKF9A4pS6eM",
      leetcodeNum: 209,
      leetcodeTitle: "Minimum Size Subarray Sum",
      leetcodeUrl: "https://leetcode.com/problems/minimum-size-subarray-sum/",
      difficulty: "Medium",
      companies: ["Amazon", "Goldman Sachs", "Google"],
      pattern: "Variable Size Window - Minimize",
      summary: "Expand window until sum >= target, then contract left pointer to find minimum valid length.",
    },
    8: {
      id: 8,
      title: "Minimum Window Substring",
      youtubeId: "jSto0O4AJbM",
      leetcodeNum: 76,
      leetcodeTitle: "Minimum Window Substring",
      leetcodeUrl: "https://leetcode.com/problems/minimum-window-substring/",
      difficulty: "Hard",
      companies: ["Meta", "Google", "Amazon", "Microsoft", "Uber"],
      pattern: "Variable Size Window - Hard",
      summary: "Track character counts required; when all matches satisfied, shrink from left to find smallest window.",
    },
    10: {
      id: 10,
      title: "Subarray Product Less Than K",
      youtubeId: "SxtxCSfSGlo",
      leetcodeNum: 713,
      leetcodeTitle: "Subarray Product Less Than K",
      leetcodeUrl: "https://leetcode.com/problems/subarray-product-less-than-k/",
      difficulty: "Medium",
      companies: ["Amazon", "Bloomberg"],
      pattern: "Variable Size Window - Counting",
      summary: "Each valid window ending at j contributes (j - i + 1) subarrays with product < k.",
    },
    11: {
      id: 11,
      title: "Maximum Points You Can Obtain from Cards",
      youtubeId: "TsA4Q_4m4uc",
      leetcodeNum: 1423,
      leetcodeTitle: "Maximum Points You Can Obtain from Cards",
      leetcodeUrl: "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/",
      difficulty: "Medium",
      companies: ["Google", "Amazon"],
      pattern: "Inverted Sliding Window",
      summary: "Taking k cards from the ends is equivalent to leaving a contiguous subarray of size (n - k) with minimum sum.",
    },
    12: {
      id: 12,
      title: "Get Equal Substrings Within Budget",
      youtubeId: "YtDls_KqIqg",
      leetcodeNum: 1208,
      leetcodeTitle: "Get Equal Substrings Within Budget",
      leetcodeUrl: "https://leetcode.com/problems/get-equal-substrings-within-budget/",
      difficulty: "Medium",
      companies: ["Google", "Adobe"],
      pattern: "Variable Size Window",
      summary: "Slide window while sum of absolute ASCII differences does not exceed maxCost.",
    },
    13: {
      id: 13,
      title: "Contains Duplicate II",
      youtubeId: "AyiQHwZ3W1U",
      leetcodeNum: 219,
      leetcodeTitle: "Contains Duplicate II",
      leetcodeUrl: "https://leetcode.com/problems/contains-duplicate-ii/",
      difficulty: "Easy",
      companies: ["Amazon", "Google"],
      pattern: "Sliding Window Set",
      summary: "Keep a hash set of size at most k; if incoming element is already in set, return true.",
    },
    15: {
      id: 15,
      title: "Binary Subarrays With Sum",
      youtubeId: "j4xydt_q1K8",
      leetcodeNum: 930,
      leetcodeTitle: "Binary Subarrays With Sum",
      leetcodeUrl: "https://leetcode.com/problems/binary-subarrays-with-sum/",
      difficulty: "Medium",
      companies: ["Amazon", "Adobe"],
      pattern: "Sliding Window (atMost(goal) - atMost(goal - 1))",
      summary: "Count exact sum by computing: countSubarraysWithSumAtMost(goal) - countSubarraysWithSumAtMost(goal - 1).",
    },
    16: {
      id: 16,
      title: "Count Number of Nice Subarrays",
      youtubeId: "4zNWYqxPnJ0",
      leetcodeNum: 1248,
      leetcodeTitle: "Count Number of Nice Subarrays",
      leetcodeUrl: "https://leetcode.com/problems/count-number-of-nice-subarrays/",
      difficulty: "Medium",
      companies: ["Amazon", "Google"],
      pattern: "Sliding Window (atMost(k) - atMost(k - 1))",
      summary: "Convert odds to 1 and evens to 0, reducing directly to Binary Subarrays With Sum.",
    },
    17: {
      id: 17,
      title: "Length of Longest Subarray With at Most K Frequency",
      youtubeId: "tZpI4c49dC8",
      leetcodeNum: 2958,
      leetcodeTitle: "Length of Longest Subarray With at Most K Frequency",
      leetcodeUrl: "https://leetcode.com/problems/length-of-longest-subarray-with-at-most-k-frequency/",
      difficulty: "Medium",
      companies: ["Google", "Amazon"],
      pattern: "Variable Size Window",
      summary: "Expand right and update element frequency; shrink left pointer until frequency is at most k.",
    },
    18: {
      id: 18,
      title: "Count Subarrays Where Max Element Appears at Least K Times",
      youtubeId: "s3_T_7hT5rY",
      leetcodeNum: 2962,
      leetcodeTitle: "Count Subarrays Where Max Element Appears at Least K Times",
      leetcodeUrl: "https://leetcode.com/problems/count-subarrays-where-max-element-appears-at-least-k-times/",
      difficulty: "Medium",
      companies: ["Google"],
      pattern: "Sliding Window - Max Element",
      summary: "First find max element in array. Once window has >= k occurrences, every start index up to left contributes a valid subarray.",
    },
    19: {
      id: 19,
      title: "Count Subarrays With Fixed Bounds",
      youtubeId: "z6LwIkEn9qc",
      leetcodeNum: 2444,
      leetcodeTitle: "Count Subarrays With Fixed Bounds",
      leetcodeUrl: "https://leetcode.com/problems/count-subarrays-with-fixed-bounds/",
      difficulty: "Hard",
      companies: ["Google", "Microsoft"],
      pattern: "Sliding Window - Index Tracking",
      summary: "Track last seen positions of minK, maxK, and invalid elements outside [minK, maxK].",
    },
    21: {
      id: 21,
      title: "Longest Continuous Subarray With Absolute Diff <= Limit",
      youtubeId: "k0TeqU1GkYY",
      leetcodeNum: 1438,
      leetcodeTitle: "Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit",
      leetcodeUrl: "https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit/",
      difficulty: "Medium",
      companies: ["Uber", "Google", "Amazon"],
      pattern: "Sliding Window + Monotonic Deque",
      summary: "Use two deques (min-deque and max-deque) to maintain window extremes in O(1) amortized time.",
    },
    23: {
      id: 23,
      title: "Longest Subarray of 1's After Deleting One Element",
      youtubeId: "O5eA_r5mU0Q",
      leetcodeNum: 1493,
      leetcodeTitle: "Longest Subarray of 1's After Deleting One Element",
      leetcodeUrl: "https://leetcode.com/problems/longest-subarray-of-1s-after-deleting-one-element/",
      difficulty: "Medium",
      companies: ["Meta", "Google"],
      pattern: "Variable Size Window (k = 1 zero)",
      summary: "Equivalent to Max Consecutive Ones with k=1, but subtract 1 from length because one element must be deleted.",
    },
    24: {
      id: 24,
      title: "Grumpy Bookstore Owner",
      youtubeId: "u_7_U4r9cM4",
      leetcodeNum: 1052,
      leetcodeTitle: "Grumpy Bookstore Owner",
      leetcodeUrl: "https://leetcode.com/problems/grumpy-bookstore-owner/",
      difficulty: "Medium",
      companies: ["Google", "Amazon"],
      pattern: "Fixed Size Window",
      summary: "Calculate guaranteed satisfied customers, then find the window of size minutes that converts the most unsatisfied customers.",
    },
    25: {
      id: 25,
      title: "K Radius Subarray Averages",
      youtubeId: "j6f8x_T_1_w",
      leetcodeNum: 2090,
      leetcodeTitle: "K Radius Subarray Averages",
      leetcodeUrl: "https://leetcode.com/problems/k-radius-subarray-averages/",
      difficulty: "Medium",
      companies: ["Meta", "Amazon"],
      pattern: "Fixed Window (Size 2*k + 1)",
      summary: "Compute running sum over window of size 2k+1 and assign average to the center index.",
    },
    26: {
      id: 26,
      title: "Frequency of the Most Frequent Element",
      youtubeId: "vgBrZ8Pz3WQ",
      leetcodeNum: 1838,
      leetcodeTitle: "Frequency of the Most Frequent Element",
      leetcodeUrl: "https://leetcode.com/problems/frequency-of-the-most-frequent-element/",
      difficulty: "Medium",
      companies: ["Google", "Amazon"],
      pattern: "Sorting + Sliding Window",
      summary: "Sort array. Expand window ending at j; cost to make all elements equal to nums[j] is nums[j]*(j-i+1) - windowSum. Shrink if cost > k.",
    },
    27: {
      id: 27,
      title: "Continuous Subarrays",
      leetcodeNum: 2762,
      leetcodeTitle: "Continuous Subarrays",
      leetcodeUrl: "https://leetcode.com/problems/continuous-subarrays/",
      difficulty: "Medium",
      companies: ["Google"],
      pattern: "Sliding Window + Ordered Map",
      summary: "Maintain difference between max and min in map <= 2; each step adds (right - left + 1) subarrays.",
    },
    30: {
      id: 30,
      title: "Count Complete Subarrays in an Array",
      leetcodeNum: 2799,
      leetcodeTitle: "Count Complete Subarrays in an Array",
      leetcodeUrl: "https://leetcode.com/problems/count-complete-subarrays-in-an-array/",
      difficulty: "Medium",
      companies: ["Amazon"],
      pattern: "Variable Window - Total Distincts",
      summary: "Once window contains all distinct elements in the whole array, every subarray starting at left and extending to the end is complete.",
    },
    31: {
      id: 31,
      title: "Count the Number of Good Subarrays",
      leetcodeNum: 2537,
      leetcodeTitle: "Count the Number of Good Subarrays",
      leetcodeUrl: "https://leetcode.com/problems/count-the-number-of-good-subarrays/",
      difficulty: "Medium",
      companies: ["Google"],
      pattern: "Sliding Window + Pair Counting",
      summary: "Track number of equal pairs in current window. When pairs >= k, shrink left while adding remaining valid subarrays.",
    },
    32: {
      id: 32,
      title: "Find the Power of K-Size Subarrays I & II",
      leetcodeNum: 3254,
      leetcodeTitle: "Find the Power of K-Size Subarrays I",
      leetcodeUrl: "https://leetcode.com/problems/find-the-power-of-k-size-subarrays-i/",
      difficulty: "Medium",
      companies: ["Amazon"],
      pattern: "Fixed Window - Consecutive Sequence",
      summary: "Maintain count of consecutive ascending elements; if count >= k, the power is nums[right], else -1.",
    },
    33: {
      id: 33,
      title: "Count of Substrings Containing Every Vowel and K Consonants II",
      leetcodeNum: 3306,
      leetcodeTitle: "Count of Substrings Containing Every Vowel and K Consonants II",
      leetcodeUrl: "https://leetcode.com/problems/count-of-substrings-containing-every-vowel-and-k-consonants-ii/",
      difficulty: "Medium",
      companies: ["Amazon", "Google"],
      pattern: "Sliding Window (atLeast(k) - atLeast(k + 1))",
      summary: "Keep count of vowels and consonants; transform exact k consonants condition using two atLeast/atMost passes.",
    },
    36: {
      id: 36,
      title: "Alternating Groups II",
      leetcodeNum: 3208,
      leetcodeTitle: "Alternating Groups II",
      leetcodeUrl: "https://leetcode.com/problems/alternating-groups-ii/",
      difficulty: "Medium",
      companies: ["Google"],
      pattern: "Circular Sliding Window",
      summary: "Concatenate or modulo-traverse array, tracking contiguous length of alternating tiles of size >= k.",
    },
    37: {
      id: 37,
      title: "Divide an Array Into Subarrays With Minimum Cost II",
      leetcodeNum: 3013,
      leetcodeTitle: "Divide an Array Into Subarrays With Minimum Cost II",
      leetcodeUrl: "https://leetcode.com/problems/divide-an-array-into-subarrays-with-minimum-cost-ii/",
      difficulty: "Hard",
      companies: ["Google"],
      pattern: "Sliding Window + Two Multisets",
      summary: "Maintain sum of smallest (k - 1) elements in a sliding window using two balanced multisets.",
    },
    38: {
      id: 38,
      title: "Find Subarray With Bitwise AND Closest to K",
      leetcodeNum: 3171,
      leetcodeTitle: "Find Subarray With Bitwise AND Closest to K",
      leetcodeUrl: "https://leetcode.com/problems/find-subarray-with-bitwise-and-closest-to-k/",
      difficulty: "Hard",
      companies: ["Google"],
      pattern: "Sliding Window + Bit Counts",
      summary: "Maintain bit count array of length 32 to compute and update window bitwise AND in O(32).",
    },
    39: {
      id: 39,
      title: "Count Substrings That Satisfy K-Constraint I & II",
      leetcodeNum: 3258,
      leetcodeTitle: "Count Substrings That Satisfy K-Constraint I",
      leetcodeUrl: "https://leetcode.com/problems/count-substrings-that-satisfy-k-constraint-i/",
      difficulty: "Easy",
      companies: ["Google", "Amazon"],
      pattern: "Variable Window - Binary String",
      summary: "Window is valid if zeros <= k OR ones <= k. Add (right - left + 1) at each step.",
    },
    40: {
      id: 40,
      title: "Maximum Difference Between Even and Odd Frequency II",
      leetcodeNum: 3445,
      leetcodeTitle: "Maximum Difference Between Even and Odd Frequency II",
      leetcodeUrl: "https://leetcode.com/problems/maximum-difference-between-even-and-odd-frequency-ii/",
      difficulty: "Hard",
      companies: ["Google"],
      pattern: "Sliding Window + Parity States",
      summary: "Pairwise character frequency optimization tracking parity states in sliding window of size >= k.",
    },
    43: {
      id: 43,
      title: "Find the Longest Substring Containing Vowels in Even Counts",
      leetcodeNum: 1371,
      leetcodeTitle: "Find the Longest Substring Containing Vowels in Even Counts",
      leetcodeUrl: "https://leetcode.com/problems/find-the-longest-substring-containing-vowels-in-even-counts/",
      difficulty: "Medium",
      companies: ["Google", "Microsoft"],
      pattern: "Bitmask + Prefix Map",
      summary: "Encode vowel parity in a 5-bit mask (0-31) and store the earliest seen index of each mask.",
    },
    44: {
      id: 44,
      title: "Count Occurences of Anagrams",
      leetcodeNum: 438,
      leetcodeTitle: "Count Occurences of Anagrams",
      leetcodeUrl: "https://leetcode.com/problems/find-all-anagrams-in-a-string/",
      difficulty: "Medium",
      companies: ["Amazon", "Flipkart"],
      pattern: "Fixed Size Window",
      summary: "Classic sliding window counting technique: maintain matching character counts with a distinct counter.",
    },
    48: {
      id: 48,
      title: "Largest Sum Subarray of Size at least K",
      leetcodeNum: 53,
      leetcodeTitle: "Maximum Subarray (Kadane + Window)",
      leetcodeUrl: "https://leetcode.com/problems/maximum-subarray/",
      difficulty: "Medium",
      companies: ["Amazon", "Samsung"],
      pattern: "Window + Kadane",
      summary: "Combine fixed window of size k with Kadane's max sum of preceding subarray.",
    },
    50: {
      id: 50,
      title: "Sliding Window Maximum (Hard)",
      youtubeId: "DfljaUwZsOk",
      leetcodeNum: 239,
      leetcodeTitle: "Sliding Window Maximum",
      leetcodeUrl: "https://leetcode.com/problems/sliding-window-maximum/",
      difficulty: "Hard",
      companies: ["Amazon", "Google", "Meta", "Uber", "Citadel"],
      pattern: "Monotonic Decreasing Deque",
      summary: "Store indices in a monotonic decreasing deque. Front of deque always stores maximum element in current window.",
    },
  },

  "sorting": {
    1: { id: 1, title: "Bubble Sort - Intuition & Optimization", leetcodeTitle: "Sort an Array", leetcodeNum: 912, leetcodeUrl: "https://leetcode.com/problems/sort-an-array/", difficulty: "Easy", pattern: "Comparison Sort", summary: "Compare adjacent elements and swap if out of order. Add swapped boolean flag for O(N) best case." },
    2: { id: 2, title: "Selection Sort - Find Minimum Element", leetcodeTitle: "Sort an Array", leetcodeNum: 912, leetcodeUrl: "https://leetcode.com/problems/sort-an-array/", difficulty: "Easy", pattern: "Comparison Sort", summary: "Iteratively find minimum in unsorted portion and swap into correct front position." },
    3: { id: 3, title: "Insertion Sort - Card Player Algorithm", leetcodeTitle: "Insertion Sort List", leetcodeNum: 147, leetcodeUrl: "https://leetcode.com/problems/insertion-sort-list/", difficulty: "Medium", pattern: "Comparison Sort", summary: "Insert key into already-sorted prefix by shifting larger elements one position to the right." },
    4: { id: 4, title: "Merge Sort - Divide and Conquer", leetcodeTitle: "Sort an Array", leetcodeNum: 912, leetcodeUrl: "https://leetcode.com/problems/sort-an-array/", difficulty: "Medium", companies: ["Google", "Amazon"], pattern: "Divide & Conquer", summary: "Recursively split array in half and merge sorted halves in O(N log N) stable time." },
    5: { id: 5, title: "Quick Sort - Lomuto vs Hoare Partition", leetcodeTitle: "Sort an Array", leetcodeNum: 912, leetcodeUrl: "https://leetcode.com/problems/sort-an-array/", difficulty: "Medium", companies: ["Amazon", "Microsoft"], pattern: "Divide & Conquer", summary: "Pick pivot, partition elements into smaller and larger, and sort partitions recursively." },
    6: { id: 6, title: "Count Inversions in an Array", leetcodeTitle: "Global and Local Inversions", leetcodeNum: 775, leetcodeUrl: "https://leetcode.com/problems/global-and-local-inversions/", difficulty: "Medium", companies: ["Google", "Amazon"], pattern: "Modified Merge Sort", summary: "Count inversions during the merge step whenever an element from right half is placed before left." },
    7: { id: 7, title: "Sort Colors (Dutch National Flag)", leetcodeTitle: "Sort Colors", leetcodeNum: 75, leetcodeUrl: "https://leetcode.com/problems/sort-colors/", difficulty: "Medium", companies: ["Microsoft", "Meta", "Amazon"], pattern: "3-Way Partitioning", summary: "One pass with three pointers: low, mid, and high to segregate 0s, 1s, and 2s in-place." },
    8: { id: 8, title: "Merge Intervals", leetcodeTitle: "Merge Intervals", leetcodeNum: 56, leetcodeUrl: "https://leetcode.com/problems/merge-intervals/", difficulty: "Medium", companies: ["Google", "Meta", "Amazon", "Apple"], pattern: "Interval Sorting", summary: "Sort intervals by start time; extend or push interval when overlap is detected." },
    9: { id: 9, title: "Non-overlapping Intervals", leetcodeTitle: "Non-overlapping Intervals", leetcodeNum: 435, leetcodeUrl: "https://leetcode.com/problems/non-overlapping-intervals/", difficulty: "Medium", companies: ["Meta", "Amazon"], pattern: "Greedy Interval Sort", summary: "Sort intervals by end time; greedily keep interval that finishes earliest." },
    10: { id: 10, title: "Custom Comparator in C++ / Java", leetcodeTitle: "Largest Number", leetcodeNum: 179, leetcodeUrl: "https://leetcode.com/problems/largest-number/", difficulty: "Medium", companies: ["Amazon", "Google"], pattern: "Custom Comparator", summary: "Sort string integers with comparator: (a + b) > (b + a). Watch out for all-zeros edge case." },
  },

  "arrays-1-d-and-2-d": {
    1: { id: 1, title: "Two Sum", leetcodeNum: 1, leetcodeTitle: "Two Sum", leetcodeUrl: "https://leetcode.com/problems/two-sum/", difficulty: "Easy", companies: ["Google", "Amazon", "Apple", "Meta"], pattern: "Hash Map / Complements", summary: "Store complement (target - num) in hash table for instant O(1) lookups in one pass." },
    2: { id: 2, title: "Best Time to Buy and Sell Stock", leetcodeNum: 121, leetcodeTitle: "Best Time to Buy and Sell Stock", leetcodeUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", difficulty: "Easy", companies: ["Amazon", "Microsoft", "Goldman Sachs"], pattern: "Greedy Min-Tracking", summary: "Track min price so far and compute max possible profit at each step." },
    3: { id: 3, title: "Majority Element (Boyer-Moore Voting)", leetcodeNum: 169, leetcodeTitle: "Majority Element", leetcodeUrl: "https://leetcode.com/problems/majority-element/", difficulty: "Easy", companies: ["Amazon", "Google"], pattern: "Boyer-Moore Voting", summary: "Maintain candidate and count. Cancel votes on mismatch, guaranteed to retain majority element in O(1) space." },
    4: { id: 4, title: "Maximum Subarray (Kadane's Algorithm)", leetcodeNum: 53, leetcodeTitle: "Maximum Subarray", leetcodeUrl: "https://leetcode.com/problems/maximum-subarray/", difficulty: "Medium", companies: ["Amazon", "Microsoft", "Apple", "Google"], pattern: "Kadane's Algorithm", summary: "Running sum accumulator: reset to current element if previous sum is negative." },
    7: { id: 7, title: "Next Permutation", leetcodeNum: 31, leetcodeTitle: "Next Permutation", leetcodeUrl: "https://leetcode.com/problems/next-permutation/", difficulty: "Medium", companies: ["Google", "Meta"], pattern: "Lexicographical Rearrangement", summary: "Find first dip from right, swap with next larger element, then reverse the remaining suffix." },
    8: { id: 8, title: "Pascal's Triangle", leetcodeNum: 118, leetcodeTitle: "Pascal's Triangle", leetcodeUrl: "https://leetcode.com/problems/pascals-triangle/", difficulty: "Easy", companies: ["Amazon", "Apple"], pattern: "Dynamic Construction", summary: "Construct row by row: each cell is sum of two directly above it in previous row." },
    9: { id: 9, title: "Set Matrix Zeroes", leetcodeNum: 73, leetcodeTitle: "Set Matrix Zeroes", leetcodeUrl: "https://leetcode.com/problems/set-matrix-zeroes/", difficulty: "Medium", companies: ["Microsoft", "Amazon"], pattern: "In-Place Matrix Marking", summary: "Use first row and first column as flag markers to achieve O(1) additional space." },
    10: { id: 10, title: "Rotate Image (90 degrees clockwise)", leetcodeNum: 48, leetcodeTitle: "Rotate Image", leetcodeUrl: "https://leetcode.com/problems/rotate-image/", difficulty: "Medium", companies: ["Google", "Amazon", "Microsoft"], pattern: "Matrix Transpose + Reverse", summary: "Transpose the matrix (swap matrix[i][j] with matrix[j][i]), then reverse each row horizontally." },
    15: { id: 15, title: "Subarray Sum Equals K", leetcodeNum: 560, leetcodeTitle: "Subarray Sum Equals K", leetcodeUrl: "https://leetcode.com/problems/subarray-sum-equals-k/", difficulty: "Medium", companies: ["Meta", "Google", "Amazon"], pattern: "Prefix Sum + Hash Map", summary: "Count frequencies of prefix sums. If (currSum - k) exists in map, add its frequency to total." },
    18: { id: 18, title: "Spiral Matrix", leetcodeNum: 54, leetcodeTitle: "Spiral Matrix", leetcodeUrl: "https://leetcode.com/problems/spiral-matrix/", difficulty: "Medium", companies: ["Microsoft", "Apple", "Google"], pattern: "Boundary Simulation", summary: "Maintain top, bottom, left, right bounds and traverse clockwise, shrinking bounds after each pass." },
    19: { id: 19, title: "Product of Array Except Self", leetcodeNum: 238, leetcodeTitle: "Product of Array Except Self", leetcodeUrl: "https://leetcode.com/problems/product-of-array-except-self/", difficulty: "Medium", companies: ["Amazon", "Apple", "Meta", "Google"], pattern: "Prefix & Suffix Products", summary: "Compute prefix products in first pass, then multiply by running suffix products in second pass in O(1) extra space." },
    22: { id: 22, title: "Insert Delete GetRandom O(1)", leetcodeNum: 380, leetcodeTitle: "Insert Delete GetRandom O(1)", leetcodeUrl: "https://leetcode.com/problems/insert-delete-getrandom-o1/", difficulty: "Medium", companies: ["Meta", "Amazon", "Google", "Bloomberg"], pattern: "Hash Map + Dynamic Array", summary: "Swap element to delete with the last array element for O(1) removal, hash map tracks index." },
    23: { id: 23, title: "Longest Consecutive Sequence", leetcodeNum: 128, leetcodeTitle: "Longest Consecutive Sequence", leetcodeUrl: "https://leetcode.com/problems/longest-consecutive-sequence/", difficulty: "Medium", companies: ["Google", "Amazon"], pattern: "Hash Set Streak", summary: "Only start counting streak if (num - 1) is not in set to ensure strictly O(N) total checks." },
    29: { id: 29, title: "Find Minimum in Rotated Sorted Array", leetcodeNum: 153, leetcodeTitle: "Find Minimum in Rotated Sorted Array", leetcodeUrl: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", difficulty: "Medium", companies: ["Amazon", "Microsoft"], pattern: "Binary Search", summary: "Compare mid with right pointer. If nums[mid] > nums[right], inflection point is to the right." },
    31: { id: 31, title: "3Sum", leetcodeNum: 15, leetcodeTitle: "3Sum", leetcodeUrl: "https://leetcode.com/problems/3sum/", difficulty: "Medium", companies: ["Meta", "Amazon"], pattern: "Two Pointers", summary: "Sort array, fix one number, then run two pointers on the remainder skipping duplicates." },
    34: { id: 34, title: "Trapping Rain Water", leetcodeNum: 42, leetcodeTitle: "Trapping Rain Water", leetcodeUrl: "https://leetcode.com/problems/trapping-rain-water/", difficulty: "Hard", companies: ["Google", "Amazon", "Goldman Sachs"], pattern: "Two Pointers", summary: "Traverse from both ends with leftMax and rightMax bounds to trap water in O(1) space." },
    48: { id: 48, title: "Continuous Subarray Sum", leetcodeNum: 523, leetcodeTitle: "Continuous Subarray Sum", leetcodeUrl: "https://leetcode.com/problems/continuous-subarray-sum/", difficulty: "Medium", companies: ["Meta", "Amazon"], pattern: "Prefix Modulo + Hash Map", summary: "Store earliest index where (prefixSum % k) was seen. If seen again with index difference >= 2, return true." },
    50: { id: 50, title: "Contiguous Array (Equal 0s and 1s)", leetcodeNum: 525, leetcodeTitle: "Contiguous Array", leetcodeUrl: "https://leetcode.com/problems/contiguous-array/", difficulty: "Medium", companies: ["Google", "Amazon"], pattern: "Prefix Sum (+1 / -1)", summary: "Treat 0 as -1 and 1 as +1. Find maximum distance between matching prefix sum occurrences." },
    58: { id: 58, title: "Candy", leetcodeNum: 135, leetcodeTitle: "Candy", leetcodeUrl: "https://leetcode.com/problems/candy/", difficulty: "Hard", companies: ["Google", "Amazon"], pattern: "Two-Pass Greedy", summary: "Left-to-right pass satisfies left neighbor condition; right-to-left pass satisfies right neighbor condition." },
    62: { id: 62, title: "Jump Game", leetcodeNum: 55, leetcodeTitle: "Jump Game", leetcodeUrl: "https://leetcode.com/problems/jump-game/", difficulty: "Medium", companies: ["Amazon", "Google", "Apple"], pattern: "Greedy Max Reach", summary: "Keep track of max reachable index so far; if current index exceeds max reach, return false." },
    64: { id: 64, title: "First Missing Positive", leetcodeNum: 41, leetcodeTitle: "First Missing Positive", leetcodeUrl: "https://leetcode.com/problems/first-missing-positive/", difficulty: "Hard", companies: ["Amazon", "Microsoft", "Google"], pattern: "Index as Hash Key", summary: "Place number x at index (x - 1) using cyclic sort swaps. First index mismatch reveals missing positive." },
    73: { id: 73, title: "Rotate Array", leetcodeNum: 189, leetcodeTitle: "Rotate Array", leetcodeUrl: "https://leetcode.com/problems/rotate-array/", difficulty: "Medium", companies: ["Amazon", "Microsoft"], pattern: "Triple Reversal Algorithm", summary: "Reverse entire array, reverse first k elements, then reverse remaining (n - k) elements in O(1) space." },
    80: { id: 80, title: "Find the Duplicate Number", leetcodeNum: 287, leetcodeTitle: "Find the Duplicate Number", leetcodeUrl: "https://leetcode.com/problems/find-the-duplicate-number/", difficulty: "Medium", companies: ["Amazon", "Google"], pattern: "Floyd's Tortoise & Hare", summary: "Treat array as linked list (index -> nums[index]). Use cycle detection to locate cycle entrance in O(1) space." },
    134: { id: 134, title: "Find the Prefix Common Array of Two Arrays", leetcodeNum: 2657, leetcodeTitle: "Find the Prefix Common Array of Two Arrays", leetcodeUrl: "https://leetcode.com/problems/find-the-prefix-common-array-of-two-arrays/", difficulty: "Medium", companies: ["Google"], pattern: "Frequency Counting", summary: "Track frequency of each element; when frequency reaches 2, increment common prefix count." },
    189: { id: 189, title: "Count Unguarded Cells in the Grid", leetcodeNum: 2257, leetcodeTitle: "Count Unguarded Cells in the Grid", leetcodeUrl: "https://leetcode.com/problems/count-unguarded-cells-in-the-grid/", difficulty: "Medium", companies: ["Google"], pattern: "Grid Ray Casting", summary: "Cast rays in 4 directions from each guard stopping at walls/guards. Count remaining unvisited cells." },
  },

  "binary-search": {
    1: { id: 1, title: "Binary Search (Fundamental)", leetcodeNum: 704, leetcodeTitle: "Binary Search", leetcodeUrl: "https://leetcode.com/problems/binary-search/", difficulty: "Easy", companies: ["Microsoft", "Apple"], pattern: "Classic Binary Search", summary: "Halve search space each step: mid = low + (high - low) / 2 to prevent integer overflow." },
    2: { id: 2, title: "Search in Rotated Sorted Array", leetcodeNum: 33, leetcodeTitle: "Search in Rotated Sorted Array", leetcodeUrl: "https://leetcode.com/problems/search-in-rotated-sorted-array/", difficulty: "Medium", companies: ["Amazon", "Google", "Meta"], pattern: "Modified Binary Search", summary: "Identify which half is sorted (left or right), and check if target falls inside that sorted range." },
    4: { id: 4, title: "Find Minimum in Rotated Sorted Array", leetcodeNum: 153, leetcodeTitle: "Find Minimum in Rotated Sorted Array", leetcodeUrl: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", difficulty: "Medium", companies: ["Amazon", "Google"], pattern: "Inflection Point Binary Search", summary: "If nums[mid] > nums[high], minimum lies in right half; otherwise it lies in left half." },
    6: { id: 6, title: "Search a 2D Matrix", leetcodeNum: 74, leetcodeTitle: "Search a 2D Matrix", leetcodeUrl: "https://leetcode.com/problems/search-a-2d-matrix/", difficulty: "Medium", companies: ["Amazon", "Microsoft"], pattern: "Virtual 1D Flattening", summary: "Treat m x n matrix as 1D array of size m*n: row = mid / n, col = mid % n." },
    9: { id: 9, title: "Find First and Last Position of Element in Sorted Array", leetcodeNum: 34, leetcodeTitle: "Find First and Last Position of Element in Sorted Array", leetcodeUrl: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/", difficulty: "Medium", companies: ["Google", "Meta", "Amazon"], pattern: "Lower Bound & Upper Bound", summary: "Run binary search twice: once biasing left for first occurrence, once biasing right for last." },
    10: { id: 10, title: "Find Peak Element", leetcodeNum: 162, leetcodeTitle: "Find Peak Element", leetcodeUrl: "https://leetcode.com/problems/find-peak-element/", difficulty: "Medium", companies: ["Google", "Meta"], pattern: "Slope Binary Search", summary: "If nums[mid] < nums[mid + 1], an upward slope guarantees a peak in the right half." },
    11: { id: 11, title: "Single Element in a Sorted Array", leetcodeNum: 540, leetcodeTitle: "Single Element in a Sorted Array", leetcodeUrl: "https://leetcode.com/problems/single-element-in-a-sorted-array/", difficulty: "Medium", companies: ["Google", "Amazon"], pattern: "Index Parity Binary Search", summary: "Pairs before the single element start on even indices (even, odd). Violation reveals left/right side." },
    13: { id: 13, title: "Capacity To Ship Packages Within D Days", leetcodeNum: 1011, leetcodeTitle: "Capacity To Ship Packages Within D Days", leetcodeUrl: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/", difficulty: "Medium", companies: ["Google", "Amazon"], pattern: "Binary Search on Answer Space", summary: "Search range [maxWeight, totalWeight]. Validate feasibility greedily for each candidate capacity." },
    14: { id: 14, title: "Koko Eating Bananas", leetcodeNum: 875, leetcodeTitle: "Koko Eating Bananas", leetcodeUrl: "https://leetcode.com/problems/koko-eating-bananas/", difficulty: "Medium", companies: ["Google", "Airbnb"], pattern: "Binary Search on Answer Space", summary: "Search eating speed k from 1 to max(piles). Calculate total hours using ceil(pile / k)." },
    18: { id: 18, title: "Magnetic Force Between Two Balls (Aggressive Cows)", leetcodeNum: 1552, leetcodeTitle: "Magnetic Force Between Two Balls", leetcodeUrl: "https://leetcode.com/problems/magnetic-force-between-two-balls/", difficulty: "Medium", companies: ["Google", "Amazon"], pattern: "Binary Search on Answer Space", summary: "Sort positions. Binary search min distance and greedily check if m balls can be placed." },
    21: { id: 21, title: "Median of Two Sorted Arrays", leetcodeNum: 4, leetcodeTitle: "Median of Two Sorted Arrays", leetcodeUrl: "https://leetcode.com/problems/median-of-two-sorted-arrays/", difficulty: "Hard", companies: ["Google", "Amazon", "Microsoft", "Apple"], pattern: "Binary Search Partitioning", summary: "Partition the smaller array such that left partition max <= right partition min in O(log(min(M,N)))." },
    32: { id: 32, title: "Successful Pairs of Spells and Potions", leetcodeNum: 2300, leetcodeTitle: "Successful Pairs of Spells and Potions", leetcodeUrl: "https://leetcode.com/problems/successful-pairs-of-spells-and-potions/", difficulty: "Medium", companies: ["Microsoft", "Goldman Sachs"], pattern: "Binary Search (Lower Bound)", summary: "Sort potions. For each spell, binary search minimum potion strength needed to reach success threshold." },
    39: { id: 39, title: "Last Day Where You Can Still Cross", leetcodeNum: 1970, leetcodeTitle: "Last Day Where You Can Still Cross", leetcodeUrl: "https://leetcode.com/problems/last-day-where-you-can-still-cross/", difficulty: "Hard", companies: ["Google"], pattern: "Binary Search + BFS / Disjoint Set", summary: "Binary search on day [1, totalCells]. Check top-to-bottom path connectivity using BFS or Union-Find." },
    50: { id: 50, title: "Maximize the Minimum Game Score", leetcodeNum: 3449, leetcodeTitle: "Maximize the Minimum Game Score", leetcodeUrl: "https://leetcode.com/problems/maximize-the-minimum-game-score/", difficulty: "Hard", companies: ["Google"], pattern: "Binary Search on Answer + Greedy", summary: "Binary search minimum target score; greedily simulate forward/backward moves to verify within m steps." },
  },

  "stack": {
    1: { id: 1, title: "Valid Parentheses", leetcodeNum: 20, leetcodeTitle: "Valid Parentheses", leetcodeUrl: "https://leetcode.com/problems/valid-parentheses/", difficulty: "Easy", companies: ["Meta", "Amazon", "Google", "Microsoft"], pattern: "Stack Matching", summary: "Push opening brackets onto stack; on closing bracket, pop and ensure matching pair." },
    2: { id: 2, title: "Min Stack", leetcodeNum: 155, leetcodeTitle: "Min Stack", leetcodeUrl: "https://leetcode.com/problems/min-stack/", difficulty: "Medium", companies: ["Amazon", "Bloomberg", "Google"], pattern: "Auxiliary Min Stack", summary: "Maintain parallel stack tracking current min at each height for O(1) getMin()." },
    3: { id: 3, title: "Evaluate Reverse Polish Notation", leetcodeNum: 150, leetcodeTitle: "Evaluate Reverse Polish Notation", leetcodeUrl: "https://leetcode.com/problems/evaluate-reverse-polish-notation/", difficulty: "Medium", companies: ["Amazon", "LinkedIn"], pattern: "Postfix Evaluation", summary: "Push operands to stack; when operator seen, pop two numbers, apply operation, and push result." },
    4: { id: 4, title: "Daily Temperatures", leetcodeNum: 739, leetcodeTitle: "Daily Temperatures", leetcodeUrl: "https://leetcode.com/problems/daily-temperatures/", difficulty: "Medium", companies: ["Meta", "Amazon", "Google"], pattern: "Monotonic Decreasing Stack", summary: "Store indices in stack. Pop indices when a warmer temperature arrives, recording day delta." },
    5: { id: 5, title: "Online Stock Span", leetcodeNum: 901, leetcodeTitle: "Online Stock Span", leetcodeUrl: "https://leetcode.com/problems/online-stock-span/", difficulty: "Medium", companies: ["Amazon", "Adobe"], pattern: "Monotonic Stack (Price, Span)", summary: "Store (price, span) pairs. Collapse smaller preceding elements into running span." },
    7: { id: 7, title: "Next Greater Element I", leetcodeNum: 496, leetcodeTitle: "Next Greater Element I", leetcodeUrl: "https://leetcode.com/problems/next-greater-element-i/", difficulty: "Easy", companies: ["Amazon"], pattern: "Monotonic Stack + Hash Map", summary: "Find next greater for all elements in nums2 using stack and save in hash map for nums1 lookups." },
    9: { id: 9, title: "Largest Rectangle in Histogram", leetcodeNum: 84, leetcodeTitle: "Largest Rectangle in Histogram", leetcodeUrl: "https://leetcode.com/problems/largest-rectangle-in-histogram/", difficulty: "Hard", companies: ["Google", "Amazon", "Meta"], pattern: "Monotonic Increasing Stack", summary: "Stack stores increasing bar heights. When height drops, pop and compute area with popped height as min." },
    10: { id: 10, title: "Maximal Rectangle (2D Matrix)", leetcodeNum: 85, leetcodeTitle: "Maximal Rectangle", leetcodeUrl: "https://leetcode.com/problems/maximal-rectangle/", difficulty: "Hard", companies: ["Google", "Amazon"], pattern: "Histogram on Matrix Rows", summary: "Accumulate consecutive 1s down rows to form histogram heights, apply Largest Rectangle in Histogram." },
    13: { id: 13, title: "Remove K Digits", leetcodeNum: 402, leetcodeTitle: "Remove K Digits", leetcodeUrl: "https://leetcode.com/problems/remove-k-digits/", difficulty: "Medium", companies: ["Google", "Amazon"], pattern: "Monotonic Increasing Stack", summary: "Greedily pop digits from stack if current incoming digit is smaller and removals remaining k > 0." },
    14: { id: 14, title: "132 Pattern", leetcodeNum: 456, leetcodeTitle: "132 Pattern", leetcodeUrl: "https://leetcode.com/problems/132-pattern/", difficulty: "Medium", companies: ["Amazon", "Google"], pattern: "Monotonic Stack from Right", summary: "Traverse from right maintaining candidate for '2' (nums[k]) with stack tracking '3' (nums[j])." },
    16: { id: 16, title: "Asteroid Collision", leetcodeNum: 735, leetcodeTitle: "Asteroid Collision", leetcodeUrl: "https://leetcode.com/problems/asteroid-collision/", difficulty: "Medium", companies: ["Amazon", "Google", "DoorDash"], pattern: "Collision Stack Simulation", summary: "Simulate right-moving (+) asteroids on stack colliding with incoming left-moving (-) asteroids." },
    21: { id: 21, title: "Minimum Add to Make Parentheses Valid", leetcodeNum: 921, leetcodeTitle: "Minimum Add to Make Parentheses Valid", leetcodeUrl: "https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/", difficulty: "Medium", companies: ["Meta", "Amazon"], pattern: "Balance Counter / Stack", summary: "Track unmatched open and closed parentheses; sum of both counters gives minimum additions." },
  },

  "heap": {
    1: { id: 1, title: "Kth Largest Element in an Array", leetcodeNum: 215, leetcodeTitle: "Kth Largest Element in an Array", leetcodeUrl: "https://leetcode.com/problems/kth-largest-element-in-an-array/", difficulty: "Medium", companies: ["Meta", "Amazon", "Google"], pattern: "Min-Heap of Size K", summary: "Maintain a min-heap of size k. Top of heap is always the kth largest element in O(N log K)." },
    2: { id: 2, title: "Top K Frequent Elements", leetcodeNum: 347, leetcodeTitle: "Top K Frequent Elements", leetcodeUrl: "https://leetcode.com/problems/top-k-frequent-elements/", difficulty: "Medium", companies: ["Amazon", "Meta", "Google"], pattern: "Frequency Map + Min-Heap / Bucket Sort", summary: "Count element frequencies, push into min-heap of size k based on frequency count." },
    3: { id: 3, title: "Find Median from Data Stream", leetcodeNum: 295, leetcodeTitle: "Find Median from Data Stream", leetcodeUrl: "https://leetcode.com/problems/find-median-from-data-stream/", difficulty: "Hard", companies: ["Google", "Amazon", "Apple"], pattern: "Two Heaps (Max-Heap + Min-Heap)", summary: "Max-heap stores smaller half, min-heap stores larger half. Balance sizes so median is readily accessible." },
    4: { id: 4, title: "Merge k Sorted Lists", leetcodeNum: 23, leetcodeTitle: "Merge k Sorted Lists", leetcodeUrl: "https://leetcode.com/problems/merge-k-sorted-lists/", difficulty: "Hard", companies: ["Amazon", "Meta", "Google"], pattern: "Min-Heap of Nodes", summary: "Push head of all k lists into min-heap. Repeatedly pop smallest node and push its next node." },
    5: { id: 5, title: "Task Scheduler", leetcodeNum: 621, leetcodeTitle: "Task Scheduler", leetcodeUrl: "https://leetcode.com/problems/task-scheduler/", difficulty: "Medium", companies: ["Meta", "Amazon"], pattern: "Max-Heap + Cooldown Queue", summary: "Greedily execute highest frequency task; hold cooling tasks in queue until interval n passes." },
    14: { id: 14, title: "IPO", leetcodeNum: 502, leetcodeTitle: "IPO", leetcodeUrl: "https://leetcode.com/problems/ipo/", difficulty: "Hard", companies: ["Google", "Amazon"], pattern: "Two Heaps / Sorting + Max-Heap", summary: "Sort projects by capital requirement. Push affordable projects into max-profit heap and greedily pick best." },
    17: { id: 17, title: "Maximum Subsequence Score", leetcodeNum: 2542, leetcodeTitle: "Maximum Subsequence Score", leetcodeUrl: "https://leetcode.com/problems/maximum-subsequence-score/", difficulty: "Medium", companies: ["Amazon"], pattern: "Sorting + Min-Heap", summary: "Sort pairs by nums2 descending. Maintain running sum of top k elements in nums1 with a min-heap." },
  },

  "bit-manipulation": {
    1: { id: 1, title: "Single Number", leetcodeNum: 136, leetcodeTitle: "Single Number", leetcodeUrl: "https://leetcode.com/problems/single-number/", difficulty: "Easy", companies: ["Google", "Amazon"], pattern: "XOR Cancellation", summary: "XOR of duplicate numbers cancels to 0 (a ^ a = 0). The surviving value is the single number." },
    2: { id: 2, title: "Single Number II", leetcodeNum: 137, leetcodeTitle: "Single Number II", leetcodeUrl: "https://leetcode.com/problems/single-number-ii/", difficulty: "Medium", companies: ["Google", "Amazon"], pattern: "Bitwise Modulo 3", summary: "Sum bits at each of the 32 positions. Modulo by 3 leaves only bits belonging to the single number." },
    3: { id: 3, title: "Single Number III", leetcodeNum: 260, leetcodeTitle: "Single Number III", leetcodeUrl: "https://leetcode.com/problems/single-number-iii/", difficulty: "Medium", companies: ["Amazon", "Google"], pattern: "Differentiating Bit Mask", summary: "XOR all numbers to get (x ^ y). Find rightmost set bit to partition array into two distinct groups." },
    4: { id: 4, title: "Number of 1 Bits (Hamming Weight)", leetcodeNum: 191, leetcodeTitle: "Number of 1 Bits", leetcodeUrl: "https://leetcode.com/problems/number-of-1-bits/", difficulty: "Easy", companies: ["Microsoft", "Apple"], pattern: "n & (n - 1) Trick", summary: "Clearing the lowest set bit with n = n & (n - 1) counts set bits in O(set_bits) steps." },
    13: { id: 13, title: "Power of Two", leetcodeNum: 231, leetcodeTitle: "Power of Two", leetcodeUrl: "https://leetcode.com/problems/power-of-two/", difficulty: "Easy", companies: ["Google"], pattern: "Bitwise Validation", summary: "A power of two has exactly one set bit: (n > 0) && ((n & (n - 1)) == 0)." },
    24: { id: 24, title: "XOR Queries of a Subarray", leetcodeNum: 1310, leetcodeTitle: "XOR Queries of a Subarray", leetcodeUrl: "https://leetcode.com/problems/xor-queries-of-a-subarray/", difficulty: "Medium", companies: ["Google"], pattern: "Prefix XOR", summary: "Compute prefix XOR array: query [L, R] evaluates in O(1) to (prefixXOR[R + 1] ^ prefixXOR[L])." },
  },
};

/**
 * Returns detailed info for a video if curated, or a smart synthesized fallback.
 */
export function getVideoDetail(slug: string, id: number, playlistName: string, playlistUrl?: string): VideoDetail {
  const curated = videoDetailsMap[slug]?.[id];
  if (curated) {
    const youtubeUrl = curated.youtubeId
      ? `https://www.youtube.com/watch?v=${curated.youtubeId}`
      : curated.youtubeUrl ||
        `https://www.youtube.com/results?search_query=${encodeURIComponent(
          `codestorywithMIK ${curated.leetcodeTitle || curated.title}`
        )}`;

    const leetcodeUrl = curated.leetcodeUrl
      ? curated.leetcodeUrl
      : curated.leetcodeTitle
      ? `https://leetcode.com/problems/${encodeURIComponent(
          curated.leetcodeTitle.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")
        )}/`
      : undefined;

    return {
      ...curated,
      youtubeUrl,
      leetcodeUrl,
    };
  }

  const ytSearchQuery = `codestorywithMIK ${playlistName} lecture ${id}`;
  const ytSearchUrl = playlistUrl
    ? `${playlistUrl}`
    : `https://www.youtube.com/results?search_query=${encodeURIComponent(ytSearchQuery)}`;

  return {
    id,
    title: `Video #${id} · ${playlistName}`,
    youtubeUrl: ytSearchUrl,
    summary: `Lecture #${id} in the ${playlistName} series by codestorywithMIK. Watch the concept breakdown, solve the corresponding interview problem, and save your notes.`,
  };
}
